update the zipkin and jaeger attributes for the instrumentation library info
open-telemetry/opentelemetry-java pull request #1724
Opened 2020-09-28 22:22 UTC by jkwatson

Resolves #1721

2020-09-29 05:45 UTC, iNikem requested changes

2020-09-29 05:45 UTC, iNikem commented on exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/Adapter.java
> +  static final String KEY_INSTRUMENTATION_LIBRARY_VERSION = "otel.instrumentation.version";
New names are `otel.library.XXX`.

2020-09-29 14:29 UTC, jkwatson commented on exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/Adapter.java
> +  static final String KEY_INSTRUMENTATION_LIBRARY_VERSION = "otel.instrumentation.version";
Crud. You are correct

2020-09-29 15:01 UTC, jkwatson commented on exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/Adapter.java
> +  static final String KEY_INSTRUMENTATION_LIBRARY_VERSION = "otel.instrumentation.version";
fixed

2020-09-30 05:22 UTC, iNikem approved these changes

2020-09-30 05:44 UTC, anuraaga approved these changes

2020-09-30 05:44 UTC, merged