Log Context's Scope.close misuse SEVERE (not FINE).
open-telemetry/opentelemetry-java pull request #1821
Opened 2020-10-16 13:00 UTC by Oberon00

We could argue about WARNING, but FINE (being disabled by default) is IMHO too low for this.

2020-10-16 16:08 UTC, carlosalberto approved these changes

2020-10-16 16:08 UTC, carlosalberto commented
Makes sense. Also, this is what grpc.Context does as well.

2020-10-16 16:33 UTC, anuraaga commented
We'll provide a proper debug mode when solving #1794. I don't think the sdk should ever have a log statement that can spam every request potentially multiple times.

2020-10-16 16:37 UTC, Oberon00 commented
This is not really in the SDK but in the context implementation, which is in theory usable without OpenTelemetry. And as @carlosalberto said, the old context implementation did the same. You can always disable the warning manually.

We also can't really record a metric for this, which we could do elsewhere in the SDK.

2020-10-16 16:41 UTC, jkwatson requested changes
Please don't merge this until we can discuss.

2020-10-16 16:42 UTC, anuraaga commented
By SDK I meant library a user adds to get telemetry - spamming logs can bring down apps and a library shouldn't do that I think. Google of course doesn't have such a problem.

2020-10-16 16:55 UTC, carlosalberto commented
> spamming logs can bring down apps and a library

Although this is totally true, closing a Context's Scope in the incorrect order ir a rather fatal scenario (in the grpc.Context docs it even says that this is the safest alternative to throwing an actual Exception). Hence I'd be up for merging this PR.

2020-10-17 02:58 UTC, anuraaga commented
I think it's only fatal to tracing, but not to an app. I'd recommend our sdk not take any risk of taking down an app by log spamming in an environment not ready for that since tracing is still a secondary function. I would encourage it to be opt in instead of default.

2020-10-17 17:22 UTC, carlosalberto commented
> I think it's only fatal to tracing, but not to an app.

If we ever want this to become an implementation that others can use (and, I think, that's the dream), instead of having Reactor, grpc and other have each its own implementation, then this change makes perfect sense, as it's an invalid, almost fatal option in general.

Even if we don't ever share it, the Specification's ideal has long be to have this as an independent layer (hence its separation as a package in the first place), that can be used by anybody who wants to integrate their cross-cutting concern with OpenTelemetry. In that regard, such users will definitely want to know when things are going wrong.

If we truly think we will only use it for Tracing, then I'd be fine with FINE, but I doubt that will be the case.

2020-10-18 02:22 UTC, anuraaga commented
@carlosalberto We can always change the log level later if it seems that is a useful change right? Let's not speculate so much for now and use a more conservative default. As I mentioned, we will be adding better tools for debugging scope issues and maybe we'll find them to be enough anyways - or maybe we'll add a metric. A log message when detaching tends to not be so informative since context propagation already broke earlier some where - what's more useful is a log message when attaching while a different local root is already attached. But that can only be done in the instrumentation layer, not here.

2020-10-18 16:07 UTC, jkwatson commented
@johnbley Do you have any thoughts here?

2020-10-18 16:53 UTC, carlosalberto commented
> We can always change the log level later if it seems that is a useful change right?

Oh definitely. But if that's the case, why don't we start with grpc.Context's default, and see how it goes? Also, I'd argue such value IS the conservative value, as it's something that has been used for long time in grpc.Context, and I don't really think it caused a big problem there :)

2020-10-20 02:25 UTC, anuraaga commented
> Also, I'd argue such value IS the conservative value, as it's something that has been used for long time in grpc.Context

That's not a conservative value, that's just cargo culting from gRPC :P If we copy everything from gRPC context, we would throw NPE on null keys which isn't allowed for OTel - in this implementation, I call `identityHashCode` instead of `key.hashCode` to avoid it, and I chuckled a bit remembering people calling grpc context a robust implementation. But it's true that server frameworks often do validate and throw exceptions - the expectations of error handling vs instrumentation is just different and we can't just blindly copy from gRPC.

Think of the team running their service on bare metal with logs stored to disk. If one API is updated to use a cool async pattern but doesn't close scope properly, it will spam the logs at least once per request. This can easily fill up the disk and cause the entire service to go down, despite nothing being wrong for the users. The SRE team will yell at the engineers again for adding a spammy log statement when they should have used metrics to have alerts without the potential of an outage.

OpenTelemetry must not have a default behavior that can cause an outage, period. And our context implementation needs to behave for this lowest common denominator, even if it does get used in cases outside of telemetry. By then we may have metrics complete and better handling than the logging anyways, so let's not speculate about this distant use case now and focus on our needs to not cause outages.

2020-10-20 02:38 UTC, trask commented
Is there any interest in logging at SEVERE/WARNING at most once a minute (and including in the message that it will only be logged at most once a minute)?

Or logging at SEVERE/WARNING only the first time it occurs (again, including in the message that it will only be logged once)?

This could be in addition to always logging at FINE.

2020-10-20 03:03 UTC, anuraaga commented
I think if we log once per call site, it would be fine at severe (sorry couldn't help it). `ConcurrentHashMap<StackTraceElement, Boolean>` could do it?

2020-10-20 07:29 UTC, Oberon00 commented
> I think if we log once per call site

That would be nice, but overkill. Maybe for now we could use a static boolean to log only the first (or a static int to log only the first 20 or so)? A more featureful throttled logger would be nice of course, but maybe too much for a lightweight context package.

2020-10-20 07:48 UTC, anuraaga commented
@Oberon00 Log just once seems fine to me too, indeed it's a lot simpler than call-site tracking.

2020-10-20 20:42 UTC, jkwatson commented
My opinion is in the "do no harm" camp. Any logging that is on by default MUST be non-disruptive. So, either opt-in to get logging, or be very restrictive in how many times we log out of the box.

2020-10-20 22:57 UTC, carlosalberto commented
> either opt-in to get logging, or be very restrictive in how many times we log out of the box.

What about allowing users to configure this? In that case we can use FINE by default, but allow users to trigger a SEVERE if the `Context` is configured through some env var or system property (and no, having the user intercept this logging does not sound very nice IMHO).

2020-10-20 23:13 UTC, jkwatson commented
> > either opt-in to get logging, or be very restrictive in how many times we log out of the box.
> 
> What about allowing users to configure this? In that case we can use FINE by default, but allow users to trigger a SEVERE if the `Context` is configured through some env var or system property (and no, having the user intercept this logging does not sound very nice IMHO).

That's this issue here, I believe:  https://github.com/open-telemetry/opentelemetry-java/issues/1794

2020-10-21 00:01 UTC, carlosalberto commented
@jkwatson Oh, I totally had forgotten about that. Yes, in that case IMHO we should follow up the SEVERE case/check as part of that.

2020-10-21 11:14 UTC, Oberon00 commented
OK then should I close this PR and this will be done as part of #1794?

2020-10-21 12:25 UTC, anuraaga commented
Really sorry @Oberon00 but that's my recommendation. I have some ideas to play with for #1794 and have wanted to after getting the instrumentation on the new context implementation in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1384 but it's been a rabbit hole of random bytecode manipulation issues 🐇

2020-10-21 13:45 UTC, Oberon00 commented
@anuraaga No problem, it's not like this PR is the result of hours of hard work 😄

2020-10-21 13:45 UTC, closed without merging