Move TraceConfig.Builder to the top level
open-telemetry/opentelemetry-java pull request #2241
Opened 2020-12-09 08:29 UTC by anuraaga

Consistency, and it looks like we get some better validation behavior (throw on set, not build) to boot.

I hadn't actually noticed we were using `Utils` here. In our meeting I think we were all ok with expecting the bom to be used to align dependencies so I'm perfectly fine with cross-referencing internal packages in this repo.

2020-12-09 16:13 UTC, bogdandrutu requested changes
The idea of offering only ToBuilder was important, because we want to ensure that you change only the parts you want and leave everything else the same in case of updating the current active config.

I think this PR changes also that behavior which should not be changed in a refactoring PR.

2020-12-09 16:46 UTC, jkwatson commented
I think we need to put a temporary hold on any changes to the SDK configuration code. We need someone to create a design document that shows the end state, so we can make sure we're all pulling in the same direction and going where we all agree we're trying to go.

2020-12-09 16:56 UTC, bogdandrutu commented
@jkwatson I don't think this is a change of configuration, this is just trying to align on the Builder not being a sub-class.

2020-12-10 00:11 UTC, anuraaga commented
@bogdandrutu Our standard pattern is `builder()` returning a builder populated with defaults, isn't it the same but less round-about than `getDefault().toBuilder()`?

2020-12-10 00:33 UTC, bogdandrutu commented
> @bogdandrutu Our standard pattern is builder() returning a builder populated with defaults, isn't it the same but less round-about than getDefault().toBuilder()?

Not necessary, the idea being that most likely devs will do mistakes when they try to Update the current config sampler for example. With your current change I am confident that someone will write without even thinking that they should start from the current config:

```java
TraceConfig traceConfig TraceConfig.builder().setSampler(foo).build();
tracerProviderSdk.UpdateConfig(traceConfig);
```

What user should do is, I think having an only `toBuilder` will trigger a thought that wait I don't want to start from default:

```java
TraceConfig traceConfig = tracerProviderSdk.CurrentConfig();
tracerProviderSdk.UpdateConfig(traceConfig.ToBuilder().setSampler(foo).build());
```

2020-12-10 00:34 UTC, bogdandrutu commented
@anuraaga also the addition of the `builder()` method is a different change than what is described in the PR, and should definitely be a separate PR.

2020-12-10 00:56 UTC, jkwatson requested changes
Blocking until we can have a comprehensive design doc that the addition of a `builder()` method either does or doesn't align with.

2020-12-10 01:14 UTC, bogdandrutu commented
@jkwatson I think this is not constructive, my suggestion of not adding the new method does not change the current code, so I am not sure I understand the motivation of doing a change that we agree already.

2020-12-10 01:16 UTC, jkwatson commented
> @jkwatson I think this is not constructive, my suggestion of not adding the new method does not change the current code, so I am not sure I understand the motivation of doing a change that we agree already on (changing the builder pattern to not be a sub-class) is blocked by a new design doc requirement

Happy to unblock if we get rid of the `builder()` method from this PR. That piece (as you rightly called out) is exposing a new configuration surface.

2020-12-10 02:51 UTC, anuraaga commented
Makes sense - removed `builder()` for now

2020-12-10 02:53 UTC, bogdandrutu approved these changes

2020-12-10 03:54 UTC, jkwatson approved these changes
Thanks! Sorry for being a PitA about this!

2020-12-10 03:54 UTC, merged

2020-12-10 03:57 UTC, bogdandrutu commented
@jkwatson always good to have check and balance :)