Have signal SDK depend on only signal API.
open-telemetry/opentelemetry-java pull request #2320
Opened 2020-12-16 09:31 UTC by anuraaga

2020-12-16 09:33 UTC, anuraaga commented on sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessor.java
> -  private static final String SPAN_PROCESSOR_TYPE_LABEL = "spanProcessorType";
We'll need to decide whether we expose a `Listener` interface to be able to push these metrics via an extension. Presumably after this PR.

2020-12-16 09:33 UTC, anuraaga commented on api/trace/src/main/java/io/opentelemetry/spi/trace/TracerProviderFactory.java
>  package io.opentelemetry.spi.trace;
I moved this file into the `api-trace` folder for now. Later we'd presumably move all the SPI into an `autoconfigure` or such artifact based on #2262

2020-12-16 17:09 UTC, bogdandrutu requested changes
Do not remove metrics from processors yet.

2020-12-16 20:12 UTC, jkwatson commented
I agree with Bogdan on this. I think we really do want those metrics in the processors and exporters; they are super valuable signals.

2020-12-16 20:25 UTC, bogdandrutu commented
> I agree with Bogdan on this. I think we really do want those metrics in the processors and exporters; they are super valuable signals.

One caveat the dependency I think can be "implementation" because we do not expose any API from the metrics publicly in this artifact

2020-12-16 23:55 UTC, anuraaga commented
I was thinking we'd need to expose a listener or such - how can we keep the metrics without forcing a user to use alpha APIs?

2020-12-17 00:59 UTC, bogdandrutu commented
> I was thinking we'd need to expose a listener or such - how can we keep the metrics without forcing a user to use alpha APIs?

Let's discuss that in a different PR :))

Also you are going to invent a new metrics API "listener", we must go deeper :))

2020-12-17 01:03 UTC, anuraaga commented
I was thinking that the next release seems like it will be quite breaking, so we would want to get as much breaking stuff in as possible. If we're splitting metrics out, ideally we split it everywhere by the next release so I made this PR. What "different PR" would be appropriate for discussiong? :P

2020-12-17 01:09 UTC, anuraaga commented
Got one idea for a different PR let me play with it.

2020-12-18 01:33 UTC, anuraaga commented
This looks like it got gobbled into #2341

2020-12-18 01:33 UTC, closed without merging