Update the metrics autoconfigure code with support for duration units.
open-telemetry/opentelemetry-java pull request #3282
Opened 2021-06-03 19:38 UTC by jkwatson

Even though metrics aren't stable yet, it seems good to have some configuration consistency.

2021-06-03 22:50 UTC, breedx-splk requested changes
Cool. I think that variable wants a little rename.

2021-06-03 22:50 UTC, breedx-splk commented on sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java
> +    Duration exportIntervalMillis = config.getDuration("otel.imr.export.interval");
probably rename that variable here too?

2021-06-03 23:40 UTC, anuraaga approved these changes
Just @breedx-splk's nit but LGTM

2021-06-04 00:21 UTC, jkwatson commented on sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java
> +    Duration exportIntervalMillis = config.getDuration("otel.imr.export.interval");
done

2021-06-04 00:53 UTC, merged