adds resource to logging span exporter
open-telemetry/opentelemetry-java pull request #5022
Opened 2022-12-07 21:33 UTC by HarryEMartland

**Is your feature request related to a problem? Please describe.**
When trying to debug building a custom distribution I was testing things using the logging span exporter so I didn't have any other dependencies. I was struggling to see the changes which I believe is due to the logging span exporter not logging the resource attributes.

**Describe the solution you'd like**
I would like the logging span exporter to also log resource attributes

**Describe alternatives you've considered**
We could create another logging span exporter which also logs resources

2022-12-09 22:27 UTC, breedx-splk requested changes
Hey thanks for the submission. I think this is a welcome change, but I had some concerns about the presentation. 

We might also want to give some consideration to whether or not people might actually be using the existing format for data export/ingest...which would imply that we probably want to make this feature configurable and default to the old behavior.

2022-12-09 22:27 UTC, breedx-splk commented on exporters/logging/src/main/java/io/opentelemetry/exporter/logging/LoggingSpanExporter.java
> +          .append(span.getResource().getAttributes());
So I'm not completely confident that this is always true, but I do believe that the resource will almost always be the same for all spans in this batch. As a result, the same information will be duplicated in the logs and will get kinda verbose.

For what it's worth, the debug logger in the collector provides output with the resource attributes at the top of the batch, followed by the span content. The output this change provides also doesn't make it super clear which set is attributes vs. resource attributes.

2022-12-09 23:00 UTC, jack-berg commented
I remember there being conversations about the logging exporter intentionally omitting resources, but can't seem to find them. I did find [this comment](https://github.com/open-telemetry/opentelemetry-java/issues/4448#issuecomment-1121474913):

>  I know our logging exporter definitely does not export the resource attributes, just to keep things light weight.

But I remember it coming up other place(s). 

Either way, if you want a more complete log of the trace, I suggest using trying [OtlpJsonLoggingSpanExporter](https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/logging-otlp/src/main/java/io/opentelemetry/exporter/logging/otlp/OtlpJsonLoggingSpanExporter.java), which logs the entire `SpanData` in the OTLP json encoding. It's verbose, but complete.

2022-12-12 20:56 UTC, HarryEMartland commented
Thanks @jack-berg, I managed to test things with the `otlp-logger`. I had to use the snapshot version for 1.21.0 so looking forward to that release as it will make debugging things easier in the future.

2022-12-13 22:44 UTC, jack-berg commented
I'm inclined to reject this given the availability of alternative more detailed logging exporters, and the noise this creates for the otherwise simple representation the logging exporters produce today.

2022-12-14 19:50 UTC, HarryEMartland commented
Makes sense to me yeah

2022-12-14 19:50 UTC, closed without merging