Use synchronized instead of reentrant lock in explicit bucket histogram
open-telemetry/opentelemetry-java pull request #6309
Opened 2024-03-19 19:38 UTC by jack-berg

Was doing some analysis and noticed a small amount of allocations occurring when recording to explicit bucket histogram.

Tracked it down and determine that ReentrantLock actually performs some small amount of allocations for synchronization. See the screenshot below from my profiler. Replaced it with the `synchronized` keyword and the allocations went away. Also noticed a modest increase in performance.

<img width="2322" alt="Screenshot 2024-03-19 at 2 35 04 PM" src="https://github.com/open-telemetry/opentelemetry-java/assets/34418638/3ae6789f-133a-4076-a72a-b9e83cce61d1">

## HistogramBenchmark

Before
```
Benchmark                                                            (aggregation)                (valueGen)  Mode  Cnt      Score       Error   Units
HistogramBenchmark.aggregate_10Threads                     EXPLICIT_DEFAULT_BUCKET   FIXED_BUCKET_BOUNDARIES  avgt   10  36837.809 ± 14387.103   ns/op
HistogramBenchmark.aggregate_10Threads:gc.alloc.rate       EXPLICIT_DEFAULT_BUCKET   FIXED_BUCKET_BOUNDARIES  avgt   10      0.005 ±     0.001  MB/sec
HistogramBenchmark.aggregate_10Threads:gc.alloc.rate.norm  EXPLICIT_DEFAULT_BUCKET   FIXED_BUCKET_BOUNDARIES  avgt   10      0.020 ±     0.007    B/op
HistogramBenchmark.aggregate_10Threads:gc.count            EXPLICIT_DEFAULT_BUCKET   FIXED_BUCKET_BOUNDARIES  avgt   10        ≈ 0              counts
HistogramBenchmark.aggregate_10Threads                     EXPLICIT_DEFAULT_BUCKET  UNIFORM_RANDOM_WITHIN_2K  avgt   10  45622.392 ±  4692.903   ns/op
HistogramBenchmark.aggregate_10Threads:gc.alloc.rate       EXPLICIT_DEFAULT_BUCKET  UNIFORM_RANDOM_WITHIN_2K  avgt   10      0.005 ±     0.001  MB/sec
HistogramBenchmark.aggregate_10Threads:gc.alloc.rate.norm  EXPLICIT_DEFAULT_BUCKET  UNIFORM_RANDOM_WITHIN_2K  avgt   10      0.026 ±     0.002    B/op
HistogramBenchmark.aggregate_10Threads:gc.count            EXPLICIT_DEFAULT_BUCKET  UNIFORM_RANDOM_WITHIN_2K  avgt   10        ≈ 0              counts
HistogramBenchmark.aggregate_10Threads                     EXPLICIT_DEFAULT_BUCKET          GAUSSIAN_LATENCY  avgt   10  47397.833 ±  3943.018   ns/op
HistogramBenchmark.aggregate_10Threads:gc.alloc.rate       EXPLICIT_DEFAULT_BUCKET          GAUSSIAN_LATENCY  avgt   10      0.005 ±     0.001  MB/sec
HistogramBenchmark.aggregate_10Threads:gc.alloc.rate.norm  EXPLICIT_DEFAULT_BUCKET          GAUSSIAN_LATENCY  avgt   10      0.026 ±     0.002    B/op
HistogramBenchmark.aggregate_10Threads:gc.count            EXPLICIT_DEFAULT_BUCKET          GAUSSIAN_LATENCY  avgt   10        ≈ 0              counts
HistogramBenchmark.aggregate_1Threads                      EXPLICIT_DEFAULT_BUCKET   FIXED_BUCKET_BOUNDARIES  avgt   10  26015.096 ±   896.893   ns/op
HistogramBenchmark.aggregate_1Threads:gc.alloc.rate        EXPLICIT_DEFAULT_BUCKET   FIXED_BUCKET_BOUNDARIES  avgt   10      0.001 ±     0.001  MB/sec
HistogramBenchmark.aggregate_1Threads:gc.alloc.rate.norm   EXPLICIT_DEFAULT_BUCKET   FIXED_BUCKET_BOUNDARIES  avgt   10      0.014 ±     0.001    B/op
HistogramBenchmark.aggregate_1Threads:gc.count             EXPLICIT_DEFAULT_BUCKET   FIXED_BUCKET_BOUNDARIES  avgt   10        ≈ 0              counts
HistogramBenchmark.aggregate_1Threads                      EXPLICIT_DEFAULT_BUCKET  UNIFORM_RANDOM_WITHIN_2K  avgt   10  34910.477 ±  1182.348   ns/op
HistogramBenchmark.aggregate_1Threads:gc.alloc.rate        EXPLICIT_DEFAULT_BUCKET  UNIFORM_RANDOM_WITHIN_2K  avgt   10      0.001 ±     0.001  MB/sec
HistogramBenchmark.aggregate_1Threads:gc.alloc.rate.norm   EXPLICIT_DEFAULT_BUCKET  UNIFORM_RANDOM_WITHIN_2K  avgt   10      0.019 ±     0.001    B/op
HistogramBenchmark.aggregate_1Threads:gc.count             EXPLICIT_DEFAULT_BUCKET  UNIFORM_RANDOM_WITHIN_2K  avgt   10        ≈ 0              counts
HistogramBenchmark.aggregate_1Threads                      EXPLICIT_DEFAULT_BUCKET          GAUSSIAN_LATENCY  avgt   10  36557.168 ±   427.892   ns/op
HistogramBenchmark.aggregate_1Threads:gc.alloc.rate        EXPLICIT_DEFAULT_BUCKET          GAUSSIAN_LATENCY  avgt   10      0.001 ±     0.001  MB/sec
HistogramBenchmark.aggregate_1Threads:gc.alloc.rate.norm   EXPLICIT_DEFAULT_BUCKET          GAUSSIAN_LATENCY  avgt   10      0.020 ±     0.001    B/op
HistogramBenchmark.aggregate_1Threads:gc.count             EXPLICIT_DEFAULT_BUCKET          GAUSSIAN_LATENCY  avgt   10        ≈ 0              counts
HistogramBenchmark.aggregate_5Threads                      EXPLICIT_DEFAULT_BUCKET   FIXED_BUCKET_BOUNDARIES  avgt   10  27350.339 ±  2304.589   ns/op
HistogramBenchmark.aggregate_5Threads:gc.alloc.rate        EXPLICIT_DEFAULT_BUCKET   FIXED_BUCKET_BOUNDARIES  avgt   10      0.003 ±     0.001  MB/sec
HistogramBenchmark.aggregate_5Threads:gc.alloc.rate.norm   EXPLICIT_DEFAULT_BUCKET   FIXED_BUCKET_BOUNDARIES  avgt   10      0.016 ±     0.002    B/op
HistogramBenchmark.aggregate_5Threads:gc.count             EXPLICIT_DEFAULT_BUCKET   FIXED_BUCKET_BOUNDARIES  avgt   10        ≈ 0              counts
HistogramBenchmark.aggregate_5Threads                      EXPLICIT_DEFAULT_BUCKET  UNIFORM_RANDOM_WITHIN_2K  avgt   10  34618.320 ±   595.322   ns/op
HistogramBenchmark.aggregate_5Threads:gc.alloc.rate        EXPLICIT_DEFAULT_BUCKET  UNIFORM_RANDOM_WITHIN_2K  avgt   10      0.003 ±     0.001  MB/sec
HistogramBenchmark.aggregate_5Threads:gc.alloc.rate.norm   EXPLICIT_DEFAULT_BUCKET  UNIFORM_RANDOM_WITHIN_2K  avgt   10      0.020 ±     0.001    B/op
HistogramBenchmark.aggregate_5Threads:gc.count             EXPLICIT_DEFAULT_BUCKET  UNIFORM_RANDOM_WITHIN_2K  avgt   10        ≈ 0              counts
HistogramBenchmark.aggregate_5Threads                      EXPLICIT_DEFAULT_BUCKET          GAUSSIAN_LATENCY  avgt   10  37097.321 ±   534.516   ns/op
HistogramBenchmark.aggregate_5Threads:gc.alloc.rate        EXPLICIT_DEFAULT_BUCKET          GAUSSIAN_LATENCY  avgt   10      0.003 ±     0.001  MB/sec
HistogramBenchmark.aggregate_5Threads:gc.alloc.rate.norm   EXPLICIT_DEFAULT_BUCKET          GAUSSIAN_LATENCY  avgt   10      0.021 ±     0.001    B/op
HistogramBenchmark.aggregate_5Threads:gc.count             EXPLICIT_DEFAULT_BUCKET          GAUSSIAN_LATENCY  avgt   10        ≈ 0              counts

```

After
```
Benchmark                                                            (aggregation)                (valueGen)  Mode  Cnt      Score     Error   Units
HistogramBenchmark.aggregate_10Threads                     EXPLICIT_DEFAULT_BUCKET   FIXED_BUCKET_BOUNDARIES  avgt   10  30270.564 ± 927.032   ns/op
HistogramBenchmark.aggregate_10Threads:gc.alloc.rate       EXPLICIT_DEFAULT_BUCKET   FIXED_BUCKET_BOUNDARIES  avgt   10      0.005 ±   0.001  MB/sec
HistogramBenchmark.aggregate_10Threads:gc.alloc.rate.norm  EXPLICIT_DEFAULT_BUCKET   FIXED_BUCKET_BOUNDARIES  avgt   10      0.017 ±   0.001    B/op
HistogramBenchmark.aggregate_10Threads:gc.count            EXPLICIT_DEFAULT_BUCKET   FIXED_BUCKET_BOUNDARIES  avgt   10        ≈ 0            counts
HistogramBenchmark.aggregate_10Threads                     EXPLICIT_DEFAULT_BUCKET  UNIFORM_RANDOM_WITHIN_2K  avgt   10  38952.976 ± 970.539   ns/op
HistogramBenchmark.aggregate_10Threads:gc.alloc.rate       EXPLICIT_DEFAULT_BUCKET  UNIFORM_RANDOM_WITHIN_2K  avgt   10      0.005 ±   0.001  MB/sec
HistogramBenchmark.aggregate_10Threads:gc.alloc.rate.norm  EXPLICIT_DEFAULT_BUCKET  UNIFORM_RANDOM_WITHIN_2K  avgt   10      0.022 ±   0.001    B/op
HistogramBenchmark.aggregate_10Threads:gc.count            EXPLICIT_DEFAULT_BUCKET  UNIFORM_RANDOM_WITHIN_2K  avgt   10        ≈ 0            counts
HistogramBenchmark.aggregate_10Threads                     EXPLICIT_DEFAULT_BUCKET          GAUSSIAN_LATENCY  avgt   10  38415.200 ± 983.709   ns/op
HistogramBenchmark.aggregate_10Threads:gc.alloc.rate       EXPLICIT_DEFAULT_BUCKET          GAUSSIAN_LATENCY  avgt   10      0.005 ±   0.001  MB/sec
HistogramBenchmark.aggregate_10Threads:gc.alloc.rate.norm  EXPLICIT_DEFAULT_BUCKET          GAUSSIAN_LATENCY  avgt   10      0.022 ±   0.001  [...]

2024-03-20 13:04 UTC, breedx-splk requested changes
Unfortunately, even though `Handle` is an inner class, instances of it are available through the `createHandle()` public method of the containing class. As such, a misbehaving user of this class could also `synchronized(handle)` and potentially form a deadlock. 

I think it should be both safer and accomplish the same goals if you were to create a `private final Object lock` and synchronize on that instead of marking the instance methods `synchronized`. Make sense?

2024-03-20 16:14 UTC, jack-berg commented
Meh.. I understand that calling code can also synchronize on the intrinsic lock, but: 1. This is internal code. 2. Doing so should always be done with caution. 

We have [examples](https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-java+synchronized&type=code&p=1) of using both the intrinsic lock and a dedicated explicit lock in internal code. Preferring one or the other is splitting hairs IMO. Let's see if any other @open-telemetry/java-approvers have a preference. If so, should probably add it to [best practices](https://github.com/open-telemetry/opentelemetry-java/blob/main/CONTRIBUTING.md#best-practices-that-we-follow).

2024-03-21 02:06 UTC, jkwatson commented
I'm with Jason on this one. It seems like a simple enough change to have an internal Object to lock on, and it will prevent having to figure out what's going on if someone decides to foot-gun themselves and synchronize on our thing.

2024-03-21 18:58 UTC, jack-berg commented
Updated to use a dedicated lock, added this advice to the best practices guide

2024-04-02 22:39 UTC, breedx-splk approved these changes
Thanks for being flexible!

2024-04-03 15:23 UTC, merged